pipeline {
    agent any

    parameters {
        string(name: 'DB_ENGINE', defaultValue: 'postgres', description: 'Database Engine')
        string(name: 'DB_INSTANCE_CLASS', defaultValue: 'db.t3.micro', description: 'DB Instance Type')
        string(name: 'DB_NAME', defaultValue: 'mydb', description: 'Database Name')
        choice(name: 'ENV', choices: ['dev', 'qa', 'prod'], description: 'Environment')
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/my-org/self-service-db.git'
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh """
                terraform plan -var="db_engine=${params.DB_ENGINE}" \
                               -var="db_instance_class=${params.DB_INSTANCE_CLASS}" \
                               -var="environment=${params.ENV}" \
                               -out=tfplan
                """
            }
        }

        stage('Approval') {
            steps {
                input "Approve DB Provisioning?"
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply tfplan'
            }
        }

        stage('Output') {
            steps {
                sh 'terraform output'
            }
        }
    }
}
