pipeline {
    agent any
    
    environment {
    AWS_REGION = 'ap-south-1'
    AWS_ACCESS_KEY_ID = credentials('062239d0-7642-458d-9972-40ce5b3ca690')   // The ID you set in Jenkins
    AWS_SECRET_ACCESS_KEY = credentials('062239d0-7642-458d-9972-40ce5b3ca690')
    TF_VAR_db_password = credentials('rds_db_password')
}


    parameters {
        string(name: 'DB_ENGINE', defaultValue: 'postgres', description: 'Database Engine')
        string(name: 'DB_INSTANCE_CLASS', defaultValue: 'db.t3.micro', description: 'DB Instance Type')
        string(name: 'DB_NAME', defaultValue: 'mydb', description: 'Database Name')
        choice(name: 'ENV', choices: ['dev', 'qa', 'prod'], description: 'Environment')
    }

    stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/ryadav0198/Aws-RDS-project.git',
                  credentialsId: 'Git-hub-details'
            }
        }

        stage('Terraform Init') {
            steps {
                sh 'terraform init'
            }
        }

        stage('Terraform Plan') {
            steps {
                sh """
                terraform plan -var="db_engine=${params.DB_ENGINE}" \
                               -var="db_instance_class=${params.DB_INSTANCE_CLASS}" \
                               -var="environment=${params.ENV}" \
                               -out=tfplan
                """
            }
        }

        stage('Approval') {
            steps {
                input "Approve DB Provisioning?"
            }
        }

        stage('Terraform Apply') {
            steps {
                sh 'terraform apply tfplan'
            }
        }

        stage('Output') {
            steps {
                sh 'terraform output'
            }
        }
    }
}
